In [ ]:
import pandas as pd

In [ ]:
baseCompra = pd.read_excel("./Base de dados desafio.xlsx")
baseCliente = pd.read_excel("./Base de dados desafio.xlsx",sheet_name='Base_cliente')

In [ ]:
pd.merge(baseCliente,baseCompra, how = 'right', left_on='cliente_Log',right_on=)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26425 entries, 0 to 26424
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   cliente_Log    26425 non-null  int64
 1   idade          26425 non-null  int64
 2   uf_nascimento  26425 non-null  object
 3   renda          26425 non-null  int64
dtypes: int64(3), object(1)
memory usage: 825.9+ KB